name = "chainlink"
version = "0.7-mock"
description = "Deploys a testing aggregator with a given rate dated into the future"
version = "<%= package.version %>"

[setting.rate]
defaultValue = "1000000000000000000"

[setting.timestamp]
# by default, its dated into the future
defaultValue = "10000000000000"

[setting.decimals]
defaultValue = "6"

[setting.salt]
defaultValue = "default"

[contract.aggregator]
artifact = "MockAggregatorV2V3"
salt = "<%= settings.salt %>"

[invoke.set_decimals]
target = ["aggregator"]
func = "setDecimals"
args = ["<%= settings.decimals %>"]
depends = ["contract.aggregator"]

[invoke.set_answer]
target = ["aggregator"]

func = "setLatestAnswer"
args = ["<%= settings.rate %>", "<%= settings.timestamp %>"]

depends = ["contract.aggregator"]
