description: Runs prod tests on a fork
parameters:
  network:
    type: string
steps:
  - cmd-fork-start:
      network: << parameters.network >>
      reset: true
  - run: npm run test:prod:gas && npx codechecks codechecks.prod.yml
