# Starts optimism-integration L1 and L2 local chains and runs Optimism integration tests against them
{{> job-header-machine.yml}}
resource_class: large
steps:
  - checkout
  - attach_workspace:
      at: .
  - run:
      name: Prepare docker containers
      command: |
        git clone git@github.com:ethereum-optimism/optimism-integration.git
        cd optimism-integration
        docker-compose -f optional/x-domain-service.yml pull
  - run:
      name: Start chains
      background: true
      command: |
        cd optimism-integration
        ./up.sh
  - cmd-wait-for-port:
        port: 8545
  - cmd-wait-for-port:
        port: 9545
  - run:
      name: Deploy OVM Synthetix instances
      command: |
        node publish deploy-ovm-pair
  - run:
      name: Run OVM production tests
      command: |
        npm run test:prod:ovm
