# Simulates a deployment of an ovm configuration in a local chain, and runs production tests against it
{{> job-header.yml}}
steps:
  - checkout
  - attach_workspace:
      at: .
  # Compile
  - run: node publish build --test-helpers
  # Start local chain
  - run:
      command: npx hardhat node
      background: true
  - cmd-wait-for-rpc
  # Deploy
  - run: node publish deploy --network local --fresh-deploy --yes --use-ovm --ignore-safety-checks --ignore-custom-parameters --deployment-path ./publish/deployed/local-ovm
  # Run production tests
  - run: npm run test:prod -- --no-compile --use-ovm --patch-fresh-deployment --deployment-path ./publish/deployed/local-ovm
