# Starts a fork of OVM, deploys the latest release, and runs L2 integration tests
{{> job-header-node.yml}}
steps:
  - checkout
  - attach_workspace:
      at: .
  - run:
      command: npm run fork:ovm
      background: true
  - cmd-wait-for-port:
      port: 8545
  - run:
      name: Run integration tests on l2
      command: |
        # Only compile and deploy when there are new contracts
        NEW_CONTRACTS=$(node bin.js sips --layer=base --unreleased --with-sources)
        if [ -z "$NEW_CONTRACTS" ]; then
          npx hardhat test:integration:l2 --compile --use-fork
        else
          npx hardhat test:integration:l2 --compile --deploy --use-sips --use-fork
        fi;
  - store_test_results:
      path: /tmp/junit/
  - store_artifacts:
      path: /tmp/junit/
