name: Synthetix CI

on:
  push:
  pull_request:
    branches: [master, develop]

jobs:
  audit:
    # run only on master/develop branch and pull requests
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/synthetixio/docker-sec-tools/base:12.21
      credentials:
        username: synthetixio
        password: ${{ secrets.GH_PACKAGES_READ_ONLY }}

    steps:
    - name: Checkout
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2

    - name: Audit dependencies
      run: npm audit --audit-level=critical

    - name: Lockfile lint
      run: lockfile-lint -p package-lock.json --type npm --allowed-hosts npm --allowed-schemes "npm:"

  build:
    needs: audit
    # run only on audit success or audit skipped
    if: always() && (needs.audit.result == 'success' || needs.audit.result == 'skipped')
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/synthetixio/docker-node/alpine:12.21
      credentials:
        username: synthetixio
        password: ${{ secrets.GH_PACKAGES_READ_ONLY }}

    steps:
    - name: Checkout
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2

    - name: Cache node modules
      uses: actions/cache@26968a09c0ea4f3e233fdddbafd1166051a095f6 # pin@v2
      with:
        path: |
          .npm
          node_modules
        key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-
      continue-on-error: true

    - name: Install dependencies
      run: npm install --no-audit

    - name: Lint:solhint
      # run only on master/develop branch and pull requests
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || github.event_name == 'pull_request'
      run: npm run lint:solhint

    - name: Lint:eslint
      # run only on master/develop branch and pull requests
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || github.event_name == 'pull_request'
      run: npm run ci:lint:eslint

    - name: Upload lint:eslint results
      # run if lint failed and only on master/develop branch and pull requests
      if: always() && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || github.event_name == 'pull_request')
      uses: github/codeql-action/upload-sarif@a3a8231e64d3db0e7da0f3b56b9521dcccdfe412 # pin@codeql-bundle-20210127
      with:
        sarif_file: lint-results.sarif
      continue-on-error: true

    - name: Cache next.js build cache
      uses: actions/cache@3b70782066bd817837b6bd8c518d45b54d91bf76 # pin@v2
      with:
        path: .next/cache
        key: ${{ runner.os }}-next.js-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-next.js-
      continue-on-error: true

    - name: Compile:evm
      run: |
        npm run compile:evm
        rm -rf build

    - name: Compile:ovm
      run: npm run compile:ovm
